#!/bin/bash

# update vxlan's configuration to enable multicast
ip link del vxlan10
ip link add name vxlan10 type vxlan id 10 dev eth0 group 239.1.1.1 dstport 4789
ip addr add 20.1.1.2/24 dev vxlan10
brctl addif br0 vxlan10
ip link set dev vxlan10 up