#!/bin/bash

# creation of static VXLAN on leaf switch
ip addr add 10.1.1.1/24 dev eth0
ip link add name vxlan10 type vxlan id 10 dev eth0 local 10.1.1.1 remote 10.1.1.2 dstport 4789
ip link set dev vxlan10 up

# creation of bridge
ip link add br0 type bridge
ip link set dev br0 up

# binding of VXLAN interface and host interface on bridge
brctl addif br0 eth1
brctl addif br0 vxlan10
