#! /bin/sh

brctl addbr br0
ip link set dev br0 up
ip link add vxlan10 type vxlan id 10 dstport 4789
ip link set dev vxlan10 up
brctl addif br0 vxlan10
brctl addif br0 eth0

vtysh -f /tmp/jcervoni_router-4_vty_conf